-- ====================================================================
-- SUPABASE CLOUD POSTGRESQL SCHEMA: CV BANONG FARMS AJIBARANG
-- Skema Basis Data Final (Bahasa Indonesia)
-- Dijalankan di: Supabase SQL Editor (supabase.com)
-- ====================================================================

-- 1. BERSIHKAN TABEL LAMA (BAIK VERSI INGGRIS MAUPUN INDONESIA)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS ai_strategies CASCADE;
DROP TABLE IF EXISTS daily_chart_metrics CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS strategi_ai CASCADE;
DROP TABLE IF EXISTS detail_pesanan CASCADE;
DROP TABLE IF EXISTS pesanan CASCADE;
DROP TABLE IF EXISTS produk CASCADE;
DROP TABLE IF EXISTS kategori CASCADE;
DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS metrik_harian CASCADE;

-- --------------------------------------------------------------------
-- 2. TABEL: admin (Metadata Profil Admin Berelasi dengan auth.users)
-- --------------------------------------------------------------------
CREATE TABLE admin (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(100) NOT NULL UNIQUE,
    nama_lengkap VARCHAR(150) NOT NULL,
    peran VARCHAR(50) NOT NULL DEFAULT 'Administrator'
);

-- --------------------------------------------------------------------
-- 3. TABEL: kategori (Master Kategori Pakan & Komoditas)
-- --------------------------------------------------------------------
CREATE TABLE kategori (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kategori VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    ikon VARCHAR(50) DEFAULT 'eco'
);

-- --------------------------------------------------------------------
-- 4. TABEL: produk (Katalog Master & Stok Fisik)
-- --------------------------------------------------------------------
CREATE TABLE produk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kategori INT REFERENCES kategori(id) ON DELETE SET NULL,
    nama_produk VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    satuan VARCHAR(50) NOT NULL DEFAULT 'kg',
    harga DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    stok INT NOT NULL DEFAULT 0,
    stok_maksimal INT NOT NULL DEFAULT 5000,
    jumlah_terjual INT NOT NULL DEFAULT 0, -- Denormalisasi untuk Kecepatan AI Analitik
    url_gambar TEXT DEFAULT '/assets/product-fertilizer.png'
);

-- --------------------------------------------------------------------
-- 5. TABEL: pesanan (Header Keranjang Belanja Pelanggan / Tiket WA)
-- --------------------------------------------------------------------
CREATE TABLE pesanan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_pesanan VARCHAR(50) NOT NULL UNIQUE,
    nama_pelanggan VARCHAR(150) NOT NULL,
    no_whatsapp VARCHAR(20) NOT NULL,
    alamat_pelanggan TEXT,
    total_harga DECIMAL(12, 2) NOT NULL DEFAULT 0.00, -- Snapshot Total Transaksi
    status VARCHAR(50) NOT NULL DEFAULT 'Menunggu Konfirmasi',
    dibuat_pada TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 6. TABEL: detail_pesanan (Rincian Barang dalam Pesanan)
-- --------------------------------------------------------------------
CREATE TABLE detail_pesanan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pesanan BIGINT NOT NULL REFERENCES pesanan(id) ON DELETE CASCADE,
    id_produk BIGINT REFERENCES produk(id) ON DELETE SET NULL,
    jumlah_beli INT NOT NULL DEFAULT 1,
    harga_satuan DECIMAL(12, 2) NOT NULL DEFAULT 0.00, -- Snapshot Harga Saat Checkout
    subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00
);

-- --------------------------------------------------------------------
-- 7. TABEL: metrik_harian (Laporan Keuangan & Data Historis AI)
-- --------------------------------------------------------------------
CREATE TABLE metrik_harian (
    tanggal DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    label_hari VARCHAR(30) NOT NULL,
    volume_aktual_kg INT NOT NULL DEFAULT 0,
    prediksi_volume_kg INT NOT NULL DEFAULT 0
);

-- --------------------------------------------------------------------
-- 8. TABEL: strategi_ai (Hasil Analisis & Rekomendasi Pemasaran AI)
-- --------------------------------------------------------------------
CREATE TABLE strategi_ai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produk_target BIGINT REFERENCES produk(id) ON DELETE SET NULL,
    teks_analisis TEXT NOT NULL,
    tingkat_akurasi VARCHAR(10) DEFAULT '95.5%'
);

-- ====================================================================
-- INDEXING
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_produk_kategori ON produk(id_kategori);
CREATE INDEX IF NOT EXISTS idx_pesanan_kode ON pesanan(kode_pesanan);
CREATE INDEX IF NOT EXISTS idx_detail_pesanan_id ON detail_pesanan(id_pesanan);
CREATE INDEX IF NOT EXISTS idx_detail_produk_id ON detail_pesanan(id_produk);

-- ====================================================================
-- DATABASE STORED PROCEDURE (RPC): TRANSAKSI PESANAN SELESAI
-- ====================================================================
CREATE OR REPLACE FUNCTION selesaikan_pesanan(p_id_pesanan BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_item RECORD;
    v_total_kg INT := 0;
    v_hari_ini DATE := CURRENT_DATE;
    v_nama_hari VARCHAR(30);
BEGIN
    -- 1. Verifikasi pesanan
    IF NOT EXISTS (SELECT 1 FROM pesanan WHERE id = p_id_pesanan AND status <> 'Selesai') THEN
        RETURN jsonb_build_object('success', false, 'message', 'Pesanan tidak ditemukan atau sudah selesai.');
    END IF;

    -- 2. Kurangi stok dan tambahkan jumlah_terjual
    FOR v_item IN SELECT id_produk, jumlah_beli FROM detail_pesanan WHERE id_pesanan = p_id_pesanan LOOP
        UPDATE produk
        SET 
            stok = GREATEST(0, stok - v_item.jumlah_beli),
            jumlah_terjual = jumlah_terjual + v_item.jumlah_beli
        WHERE id = v_item.id_produk;
        
        v_total_kg := v_total_kg + v_item.jumlah_beli;
    END LOOP;

    -- 3. Update status pesanan
    UPDATE pesanan 
    SET status = 'Selesai' 
    WHERE id = p_id_pesanan;

    -- 4. Tentukan nama hari
    v_nama_hari := CASE EXTRACT(DOW FROM v_hari_ini)
        WHEN 0 THEN 'Minggu'
        WHEN 1 THEN 'Senin'
        WHEN 2 THEN 'Selasa'
        WHEN 3 THEN 'Rabu'
        WHEN 4 THEN 'Kamis'
        WHEN 5 THEN 'Jumat'
        WHEN 6 THEN 'Sabtu'
    END;

    -- 5. Akumulasi volume ke metrik harian
    INSERT INTO metrik_harian (tanggal, label_hari, volume_aktual_kg, prediksi_volume_kg)
    VALUES (v_hari_ini, v_nama_hari, v_total_kg, v_total_kg + 50)
    ON CONFLICT (tanggal) 
    DO UPDATE SET 
        volume_aktual_kg = metrik_harian.volume_aktual_kg + EXCLUDED.volume_aktual_kg;

    RETURN jsonb_build_object('success', true, 'message', 'Pesanan berhasil divalidasi. Stok terpotong dan metrik harian diperbarui.');
END;
$$;

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================
ALTER TABLE admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE kategori ENABLE ROW LEVEL SECURITY;
ALTER TABLE produk ENABLE ROW LEVEL SECURITY;
ALTER TABLE pesanan ENABLE ROW LEVEL SECURITY;
ALTER TABLE detail_pesanan ENABLE ROW LEVEL SECURITY;
ALTER TABLE metrik_harian ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategi_ai ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Publik Boleh Lihat Kategori" ON kategori FOR SELECT USING (true);
CREATE POLICY "Admin Full Akses Kategori" ON kategori FOR ALL TO authenticated USING (true);

CREATE POLICY "Publik Boleh Lihat Produk" ON produk FOR SELECT USING (true);
CREATE POLICY "Publik Boleh Tambah Produk" ON produk FOR INSERT WITH CHECK (true);
CREATE POLICY "Publik Boleh Update Produk" ON produk FOR UPDATE USING (true);
CREATE POLICY "Publik Boleh Hapus Produk" ON produk FOR DELETE USING (true);
CREATE POLICY "Admin Full Akses Produk" ON produk FOR ALL TO authenticated USING (true);

CREATE POLICY "Publik Boleh Checkout Pesanan" ON pesanan FOR INSERT WITH CHECK (true);
CREATE POLICY "Publik Boleh Lihat Pesanan" ON pesanan FOR SELECT USING (true);
CREATE POLICY "Publik Boleh Update Pesanan" ON pesanan FOR UPDATE USING (true);
CREATE POLICY "Admin Full Akses Pesanan" ON pesanan FOR ALL TO authenticated USING (true);

CREATE POLICY "Publik Boleh Tambah Detail Pesanan" ON detail_pesanan FOR INSERT WITH CHECK (true);
CREATE POLICY "Publik Boleh Lihat Detail Pesanan" ON detail_pesanan FOR SELECT USING (true);
CREATE POLICY "Admin Full Akses Detail Pesanan" ON detail_pesanan FOR ALL TO authenticated USING (true);

CREATE POLICY "Publik Boleh Lihat Metrik" ON metrik_harian FOR SELECT USING (true);
CREATE POLICY "Admin Full Akses Metrik" ON metrik_harian FOR ALL TO authenticated USING (true);

CREATE POLICY "Publik Boleh Lihat Strategi AI" ON strategi_ai FOR SELECT USING (true);
CREATE POLICY "Admin Full Akses Strategi AI" ON strategi_ai FOR ALL TO authenticated USING (true);

CREATE POLICY "Akses Profil Admin" ON admin FOR ALL TO authenticated USING (true);

-- ====================================================================
-- AKTIFKAN SUPABASE REALTIME REPLICATION (WEBSOCKET)
-- ====================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE produk;
ALTER PUBLICATION supabase_realtime ADD TABLE pesanan;
ALTER PUBLICATION supabase_realtime ADD TABLE metrik_harian;

-- ====================================================================
-- SEED DATA AWAL (KATALOG PAKAN CV BANONG FARMS)
-- ====================================================================
INSERT INTO kategori (id, nama_kategori, slug, ikon) VALUES
(1, 'Pakan Unggas & Bebek', 'unggas', 'egg'),
(2, 'Pakan Ikan Air Tawar', 'ikan', 'set_meal'),
(3, 'Pakan Ternak Ruminansia', 'ruminansia', 'nutrition'),
(4, 'Pupuk & Olahan Organik', 'organik', 'eco')
ON CONFLICT (id) DO NOTHING;

INSERT INTO produk (id, id_kategori, nama_produk, deskripsi, satuan, harga, stok, stok_maksimal, jumlah_terjual, url_gambar) VALUES
(1, 1, 'Konsentrat Bebek Petelur Super', 'Pakan formulasi asam amino lengkap untuk mengoptimalkan produksi kuning telur jingga alami peternakan Ajibarang.', 'karung 50kg', 425000.00, 180, 500, 120, '/assets/product-eggs.png'),
(2, 2, 'Pelet Ikan Lele Apung LP-2', 'Pelet apung protein 32% cocok untuk pembesaran lele kolam air deras Ajibarang.', 'karung 30kg', 315000.00, 240, 600, 310, '/assets/product-fish.png'),
(3, 3, 'Silase Pakan Fermentasi Sapi & Kambing', 'Hijauan jagung manis terfermentasi bakteri asam laktat, tahan hingga 8 bulan.', 'drum 100kg', 185000.00, 95, 300, 75, '/assets/product-chicken.png'),
(4, 4, 'Pupuk Organik Kasgot Biokonversi', 'Pupuk hayati kaya hara makro hasil biokonversi limbah organik larva maggot BSF.', 'karung 25kg', 65000.00, 500, 1000, 420, '/assets/product-fertilizer.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metrik_harian (tanggal, label_hari, volume_aktual_kg, prediksi_volume_kg) VALUES
(CURRENT_DATE - INTERVAL '3 days', 'Senin', 1450, 1400),
(CURRENT_DATE - INTERVAL '2 days', 'Selasa', 1820, 1750),
(CURRENT_DATE - INTERVAL '1 days', 'Rabu', 2100, 2000),
(CURRENT_DATE, 'Kamis', 2450, 2300)
ON CONFLICT (tanggal) DO NOTHING;
