/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#022448",
        "primary-container": "#1e3a5f",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#adc8f5",
        "on-primary": "#ffffff",
        "on-primary-container": "#8aa4cf",
        "navy-dark": "#13253D",
        "navy-muted": "#3D5A80",
        
        "secondary": "#705d00",
        "secondary-container": "#fcd400",
        "secondary-fixed": "#ffe16d",
        "secondary-fixed-dim": "#e9c400",
        "on-secondary-container": "#6e5c00",
        "accent-hover": "#E6C200",
        
        "tertiary": "#1E3A5F",
        "tertiary-container": "#E2E8F0",
        "tertiary-fixed": "#F1F5F9",
        "tertiary-fixed-dim": "#CBD5E1",
        "on-tertiary-fixed-variant": "#334155",
        "on-tertiary-container": "#022448",
        
        "whatsapp-green": "#fcd400",
        "whatsapp-hover": "#e6c200",
        "alert-badge": "#EF4444",
        
        "surface-pure": "#FFFFFF",
        "surface-subtle": "#F8FAFC",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        
        "on-surface": "#191c1e",
        "on-surface-variant": "#43474e",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "error": "#ba1a1a",
        
        // Command Center specific tokens
        "shell-base": "rgba(0, 0, 0, 0.70)",
        "shell-border": "rgba(255, 255, 255, 0.12)",
        "on-shell": "#ffffff",
        "on-shell-muted": "rgba(255, 255, 255, 0.70)",
        "cc-orange": "#fe6e00",
        "cc-orange-strong": "#ff6b00",
        "cc-orange-warm": "#ffb74d",
        "cc-orange-focus": "#f97015",
        "cc-bg": "#fbf9f6",
        "cc-surface": "#ffffff",
        "cc-surface-muted": "#f3f4f6",
        "cc-surface-soft": "#edebe9",
        "cc-outline": "#e3e0dd",
        "status-production-bg": "#dcfce7",
        "status-production-fg": "#016630",
        "status-mock-bg": "#fef9c2",
        "status-mock-fg": "#874b00",
        "status-integrated-bg": "#f3e8ff",
        "status-integrated-fg": "#8200da",
        "status-development-bg": "#dbeafe",
        "status-development-fg": "#1447e6",
        "status-planned-bg": "#f3f4f6",
        "status-planned-fg": "#364153",
      },
      spacing: {
        "space-2": "0.125rem",
        "space-4": "0.25rem",
        "space-8": "0.5rem",
        "space-12": "0.75rem",
        "space-16": "1rem",
        "space-20": "1.25rem",
        "space-24": "1.5rem",
        "space-32": "2rem",
        "space-40": "2.5rem",
        "space-48": "3rem",
        "space-64": "4rem",
        "space-80": "5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "container-max": "1280px",
        
        // Command Center layout spacing
        "shell-header-height": "4rem",
        "shell-sidebar-expanded": "16rem",
        "shell-sidebar-collapsed": "4rem",
        "content-max-width": "87.5rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "2.5rem",
        "space-3xl": "4rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Inter", "sans-serif"],
        "telemetry-code": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["16px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        zoomIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        }
      },
      animation: {
        float: 'float 3s ease-in-out infinite',
        'fade-in': 'fadeIn 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-down': 'fadeInDown 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'zoom-in': 'zoomIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      }
    },
  },
  plugins: [],
}
